name: FIE and EuroFencing Scrape, PDF, Email and update MySQL

on:
  schedule:
    - cron: "0 6 * * 2" # 6am every Tuesday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager fake-useragent beautifulsoup4 pandas certifi pymysql sqlalchemy fpdf datetime lxml

      - name: Install Edge
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          wget https://packages.microsoft.com/keys/microsoft.asc
          sudo apt-key add microsoft.asc
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable
          sudo apt-get install -y wget unzip xvfb
          rm microsoft.asc  # Clean up the file after use

      - name: Verify Edge Installation
        run: microsoft-edge --version

      - name: Run FIE scrape script
        run: python Scraper_FIE_Rankings.py

      - name: Run EUROFENCING scrape script
        env:
          DISPLAY: ":99.0"
        run: |
          Xvfb :99 -ac &
          # Retry Xvfb start if needed
          for i in {1..5}; do if xdpyinfo -display :99 > /dev/null 2>&1; then break; else sleep 1; fi; done
          python Scraper_EuroFencing_Rankings.py

      - name: Commit and push changes if necessary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add Eurofencing_Individual_Rankings.csv FIE_Ranking_data.csv Ranking_PDF_reports/Fencing_Ranking_Report_*.pdf
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update weekly FIE and Eurofencing csvs, push to Databases, PDF and email"
            git push origin HEAD:main
          fi

      - name: Run PDF and Email script
        run: |
          python PDF_and_Email.py

      - name: Update Aiven MySQL Database for FIE and Eurofencing
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          python mySQL_update.py




